# SPDX-FileCopyrightText: 2023 Baking Bad <hello@bakingbad.dev>
#
# SPDX-License-Identifier: MIT

version: "3.8"
services:
  etherlink-operator:
    image: etherlink:${TAG}
    container_name: 'etherlink-operator'
    command: run_node
    restart: "no"
    env_file:
      - .env
      # TAG e.g. v18 or master
      # NETWORK e.g. oxfordnet
      # ROLLUP_ADDRESS e.g. sr1...
      # OPERATOR_KEY e.g. unencrypted:edsk...
    volumes:
      - .tezos-client:/root/.tezos-client/
      - .tezos-smart-rollup-node:/root/.tezos-smart-rollup-node
    ports:
      - 8932:8932
    networks:
      - internal

  etherlink-facade:
    image: etherlink:${TAG}
    container_name: 'etherlink-facade'
    entrypoint: /usr/bin/octez-evm-node
    command: run proxy with endpoint http://etherlink-operator:8932 --rpc-addr "0.0.0.0" --rpc-port 8545
    restart: always
    ports:
      - 8545:8545
    networks:
      - internal

  blockscout-redis-db:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    container_name: blockscout-redis-db
    command: redis-server
    volumes:
      - ./redis-data:/data
    networks:
      - internal

  blockscout-db:
    image: postgres:14
    restart: always
    container_name: 'blockscout-db'
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data/
    networks:
      - internal

  blockscout:
    depends_on:
      - blockscout-db
      - blockscout-redis-db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    restart: always
    stop_grace_period: 5m
    container_name: 'blockscout'
    links:
      - blockscout-db:database
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
      SUBNETWORK: Etherlink
      CHAIN_ID: 128123
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: true
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: true
      MICROSERVICE_SC_VERIFIER_ENABLED: false
      MICROSERVICE_VISUALIZE_SOL2UML_ENABLED: false
      MICROSERVICE_SIG_PROVIDER_ENABLED: false
      DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
      ACCOUNT_REDIS_URL: redis://blockscout-redis-db:6379
    ports:
      - 4000:4000
    volumes:
      - ./logs/:/app/logs/
    networks:
      - internal

networks:
  internal:
